config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :menus
  end
  #前端网页控制器。
  namespace :mobile do
    #命名空间默认控制器
    get '', to: 'static_pages#home', as: '/'
    get 'static_pages', to: 'static_pages#home', as: 'static_pages/'
    get 'static_pages/home'
  end


  ##AUTHENTICATION
  namespace :admin do
    #跳转至登录界面；
    get 'logout', to: 'login#logout', as: 'logout/'
    get 'login/logout'

    #跳转至登录界面；
    get 'login', to: 'login#login', as: 'login/'
    get 'login/login'

    #表单提交验证；
    post 'login', to: 'login#signin', as: 'signin/'
    post 'login/signin'

    #跳转至主界面；
    get 'main', to: 'main#index', as: 'main/'
    get 'main/index'
    get '/', to: 'main#index', as: '/'

    resources :users

    resources :channels
  end

  #root 'index.html'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/channel.rb
class Admin::Channel < ApplicationRecord
end

app/controllers/admin/channels_controller.rb
class Admin::ChannelsController < ApplicationController
  before_action :set_admin_channel, only: [:show, :edit, :update, :destroy]

  # GET /admin/channels
  # GET /admin/channels.json
  def index
    @admin_channels = Admin::Channel.all
    printf("Pi is about %.4f", Math::PI)
  end

  # GET /admin/channels/1
  # GET /admin/channels/1.json
  def show
  end

  # GET /admin/channels/new
  def new
    @admin_channel = Admin::Channel.new
  end

  # GET /admin/channels/1/edit
  def edit
  end

  # POST /admin/channels
  # POST /admin/channels.json
  def create
    @admin_channel = Admin::Channel.new(admin_channel_params)

    respond_to do |format|
      if @admin_channel.save
        format.html { redirect_to @admin_channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @admin_channel }
      else
        format.html { render :new }
        format.json { render json: @admin_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/channels/1
  # PATCH/PUT /admin/channels/1.json
  def update
    respond_to do |format|
      if @admin_channel.update(admin_channel_params)
        format.html { redirect_to @admin_channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_channel }
      else
        format.html { render :edit }
        format.json { render json: @admin_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/channels/1
  # DELETE /admin/channels/1.json
  def destroy
    @admin_channel.destroy
    respond_to do |format|
      format.html { redirect_to admin_channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_channel
      @admin_channel = Admin::Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_channel_params
      params.require(:admin_channel).permit(:name, :parent_id, :created_by, :updated_by)
    end
end

app/helpers/admin/channels_helper.rb
module Admin::ChannelsHelper
end

app/views/admin/channels/_form.html.erb
<%= form_for(admin_channel) do |f| %>
  <% if admin_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_channel.errors.count, "error") %> prohibited this admin_channel from being saved:</h2>

      <ul>
      <% admin_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :parent_id %>
    <%= f.number_field :parent_id %>
  </div>

  <div class="field">
    <%= f.label :created_by %>
    <%= f.text_field :created_by %>
  </div>

  <div class="field">
    <%= f.label :updated_by %>
    <%= f.text_field :updated_by %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/channels/edit.html.erb
<h1>Editing Admin Channel</h1>

<%= render 'form', admin_channel: @admin_channel %>

<%= link_to 'Show', @admin_channel %> |
<%= link_to 'Back', admin_channels_path %>

app/views/admin/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_channels.each do |admin_channel| %>
      <tr>
        <td><%= admin_channel.name %></td>
        <td><%= admin_channel.parent_id %></td>
        <td><%= admin_channel.created_by %></td>
        <td><%= admin_channel.updated_by %></td>
        <td><%= link_to 'Show', admin_channel %></td>
        <td><%= link_to 'Edit', edit_admin_channel_path(admin_channel) %></td>
        <td><%= link_to 'Destroy', admin_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建栏目', new_admin_channel_path %>

app/views/admin/channels/new.html.erb
<h1>New Admin Channel</h1>

<%= render 'form', admin_channel: @admin_channel %>

<%= link_to 'Back', admin_channels_path %>

app/views/admin/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_channel.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @admin_channel.parent_id %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @admin_channel.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @admin_channel.updated_by %>
</p>

<%= link_to 'Edit', edit_admin_channel_path(@admin_channel) %> |
<%= link_to 'Back', admin_channels_path %>