config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :menus
  end
  #前端网页控制器。
  namespace :mobile do
    #命名空间默认控制器
    get '', to: 'static_pages#home', as: '/'
    get 'static_pages', to: 'static_pages#home', as: 'static_pages/'
    get 'static_pages/home'
  end


  ##AUTHENTICATION
  namespace :admin do
    #跳转至登录界面；
    get 'logout', to: 'login#logout', as: 'logout/'
    get 'login/logout'

    #跳转至登录界面；
    get 'login', to: 'login#login', as: 'login/'
    get 'login/login'

    #表单提交验证；
    post 'login', to: 'login#signin', as: 'signin/'
    post 'login/signin'

    #跳转至主界面；
    get 'main', to: 'main#index', as: 'main/'
    get 'main/index'
    get '/', to: 'main#index', as: '/'

    resources :users

    resources :channels
  end

  #root 'index.html'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord
  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AuthencatedController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:username, :password, :password_confirmation, :created_by, :updated_by, :email, :gender, :mobile, :enabled, :real_name, :is_enabled, :is_locked, :is_expired, :status, :type)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(admin_user , html: {class: "form-horizontal",style:"max-width: 600px;"})  do |f|  %>
<% if admin_user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

  <ul>
    <% admin_user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%# <label for="inputUsername" class="sr-only">用户名</label>
<input type="text" id="inputUsername" name="username" class="form-control" style="margin-bottom:10px"  placeholder="用户名" required autofocus>
  %>

<div class="form-group">
  <%= f.label :username ,"用户名",class:"col-md-2 control-label",style:"color:red"%>
  <div class="col-md-10">
    <%= f.text_field :username , size: "30", class:"form-control" , placeholder:"用户名",required:true %>
  </div>
</div>

<div class="form-group">
  <%= f.label :password ,"密  码",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.password_field :password  , class:"form-control" , placeholder:"密  码",required:true%>
  </div>
</div>

<div class="form-group">
  <%= f.label :password_confirmation ,"确认密码",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.password_field :password_confirmation   , class:"form-control" , placeholder:"确认密码",required:true%>
  </div>
</div>

<div class="form-group">
  <%= f.label :real_name  ,"真实姓名",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.text_field :real_name   , class:"form-control" , placeholder:"真实姓名",required:true,autofocus:true%>
  </div>
</div>

<div class="form-group">
  <%= f.label :email ,"邮  箱",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.email_field :email , class:"form-control" , placeholder:"邮  箱",required:true%>
  </div>
</div>

<div class="form-group">
  <%= f.label :mobile ,"电  话",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.text_field :mobile  , class:"form-control" , placeholder:"电  话",required:true%>
  </div>
</div>

<div class="form-group">
  <%= f.label :gender,"性  别",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <div class="radio">
      <label>
        <%=f.radio_button(:gender, true)%>男
      </label>
      <label>
          <%=f.radio_button(:gender, false)%>女
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :is_enabled  ,"是否可用",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <div class="radio">
      <label>
        <%=f.radio_button(:is_enabled, true)%>是
      </label>
      <label>
        <%=f.radio_button(:is_enabled, false)%>否
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :is_locked ,"是否锁定",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <div class="radio">
      <label>
        <%=f.radio_button(:is_locked, true)%>是
      </label>
      <label>
        <%=f.radio_button(:is_locked, false)%>否
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :is_expired ,"是否过期",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <div class="radio">
      <label>
        <%=f.radio_button(:is_expired, true)%>是
      </label>
      <label>
        <%=f.radio_button(:is_expired, false)%>否
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :status,"状态",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.number_field :status %>
  </div>
</div>

<div class="form-group">
  <%= f.label :type ,"类型",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.number_field :type %>
  </div>
</div>

<div class="actions form-group">
  <div class="col-md-2"></div>
  <div class="col-md-10">
    <%= f.submit "提交", class:"btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/admin/users/_index.html.erb
<ul class="breadcrumb">
  <li><a href="/admin/main">首页</a></li>
  <li><a href="/admin/users" class="active">用户管理</a></li>
</ul>
<p id="notice"><%= notice %></p>
<h4 class="sub-header">用户列表</h4>
<%= link_to raw("<i class=\"fa fa-plus\" aria-hidden=\"true\">&nbsp;添加用户</i>"), new_admin_user_path  ,{ class:'btn btn-success'}%>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="text-align: center;">用户名</th>
                <th style="text-align: center;">邮箱</th>
                <th style="text-align: center;">性别</th>
                <th style="text-align: center;">电话</th>
                <th style="text-align: center;">是否可用</th>
                <th style="text-align: center;">实名</th>
                <th style="text-align: center;">是否锁定</th>
                <th style="text-align: center;">是否过期</th>
                <th style="text-align: center;">状态</th>
                <th style="text-align: center;">类型</th>
                <th colspan="3" style="text-align: center;">操作</th>
            </tr>
        </thead>
        <tbody>
            <% @admin_users.each do |admin_user| %>
            <tr>
                <td><%= admin_user.username %></td>
                <td style="text-align: center;"><%= admin_user.email %></td>
                <td style="text-align: center;">
                        <label>
                        <% if admin_user.gender== true %>
                            <%= "男"%>
                        <% else %>
                            <%= "女"%>
                        <% end %>
                        </label>
                </td>
                <td style="text-align: center;"><%= admin_user.mobile %></td>
                <td style="text-align: center;">
                    <label>
                        <% if admin_user.is_enabled== true %>
                            <%= "是"%>
                        <% else %>
                            <%= "否"%>
                        <% end %>
                        </label>
                </td>
                <td><%= admin_user.real_name %></td>
                <td style="text-align: center;">
                    <label>
                        <% if admin_user.is_locked== true %>
                            <%= "是"%>
                        <% else %>
                            <%= "否"%>
                        <% end %>
                        </label>
                </td>
                <td style="text-align: center;">
                    <label>
                        <% if admin_user.is_expired== true %>
                            <%= "是"%>
                        <% else %>
                            <%= "否"%>
                        <% end %>
                        </label>
                </td>
                <td><%= admin_user.status %></td>
                <td><%= admin_user.type %></td>
                <td><%= link_to raw("<i class=\"fa fa-info-circle\" aria-hidden=\"true\">&nbsp;详情</i>"), admin_user ,{ class:'btn btn-info'}%></td>
                <td><%= link_to raw("<i class=\"fa fa-wrench\" aria-hidden=\"true\">&nbsp;编辑</i>"), edit_admin_user_path(admin_user) ,{ class:'btn btn-warning'}%></td>
                <td><%= link_to raw("<i class=\"fa fa-trash\" aria-hidden=\"true\">&nbsp;删除</i>"), admin_user, method: :delete, data: { confirm: '你确定删除该条目吗?' },class:'btn btn-danger'%></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/users/edit.html.erb
<%@title="管理后台用户编辑页"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar" , select_menu: "/admin/users" %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <ul class="breadcrumb">
          <li><a href="/admin/main">首页</a></li>
          <li><a href="/admin/users" class="active">用户管理</a></li>
          <%# <li><a class="active">用户编辑</a></li> %>
        </ul>
        <h4 class="sub-header">用户编辑</h4>
        <%= render 'form', admin_user: @admin_user %>
        <%= link_to raw("<i class=\"fa fa-wrench\" aria-hidden=\"true\">&nbsp;详情</i>"), @admin_user ,{ class:'btn btn-info'}%>
        <%= link_to raw("<i class=\"fa fa-arrow-circle-left\" aria-hidden=\"true\">&nbsp;返回</i>"), admin_users_path ,{ class:'btn btn-primary'}%>

        <%# link_to '详情', @admin_user %> 
        <%# link_to '返回', admin_users_path %>
    </div>  
  </div>
</div>
<script type="text/javascript">
    $(function(){ 
　　  document.getElementById("admin_user_username").disabled=true;
        $('#admin_user_username').attr("disabled",true);
　　});
</script>

app/views/admin/users/index.html.erb
<%@title="管理后台用户首页"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar", select_menu: "/admin/users" %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <%= render "admin/users/index"%> 
    </div>  
  </div>
</div>

app/views/admin/users/new.html.erb
<%@title="管理后台新建用户"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar", select_menu: "/admin/users"  %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <ul class="breadcrumb">
          <li><a href="/admin/main">首页</a></li>
          <li><a href="/admin/users" class="active">用户管理</a></li>
          <%# <li><a class="active">用户新增</a></li> %>
      </ul>
      <h4 class="sub-header">新建用户</h4>
      
      <%= render 'form', admin_user: @admin_user %>
      <%= link_to raw("<i class=\"fa fa-arrow-circle-left\" aria-hidden=\"true\">&nbsp;返回</i>"), admin_users_path ,{ class:'btn btn-primary'}%>
    </div>  
  </div>
</div>

app/views/admin/users/show.html.erb
<%@title="管理后台用户详情"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar", select_menu: "/admin/users"  %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <ul class="breadcrumb">
          <li><a href="/admin/main">首页</a></li>
          <li><a href="/admin/users" class="active">用户管理</a></li>
          <%# <li><a href="#" class="active">用户详情</a></li> %>
      </ul>
        <h4 class="sub-header">用户详情</h4>
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Username:</strong>
          <%= @admin_user.username %>
        </p>

        <p>
          <strong>Created by:</strong>
          <%= @admin_user.created_by %>
        </p>

        <p>
          <strong>Updated by:</strong>
          <%= @admin_user.updated_by %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @admin_user.email %>
        </p>

        <p>
          <strong>Gender:</strong>
          <%= @admin_user.gender %>
        </p>

        <p>
          <strong>Mobile:</strong>
          <%= @admin_user.mobile %>
        </p>

        <p>
          <strong>Enabled:</strong>
          <%= @admin_user.enabled %>
        </p>

        <p>
          <strong>Real name:</strong>
          <%= @admin_user.real_name %>
        </p>

        <p>
          <strong>Is enabled:</strong>
          <%= @admin_user.is_enabled %>
        </p>

        <p>
          <strong>Is locked:</strong>
          <%= @admin_user.is_locked %>
        </p>

        <p>
          <strong>Is expired:</strong>
          <%= @admin_user.is_expired %>
        </p>

        <p>
          <strong>Status:</strong>
          <%= @admin_user.status %>
        </p>

        <p>
          <strong>Type:</strong>
          <%= @admin_user.type %>
        </p>
        <%= link_to raw("<i class=\"fa fa-wrench\" aria-hidden=\"true\">&nbsp;编辑</i>"), edit_admin_user_path(@admin_user) ,{ class:'btn btn-warning'}%>
        <%= link_to raw("<i class=\"fa fa-arrow-circle-left\" aria-hidden=\"true\">&nbsp;返回</i>"), admin_users_path ,{ class:'btn btn-primary'}%>

    </div>  
  </div>
</div>