config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :menus
  end
  #前端网页控制器。
  namespace :mobile do
    #命名空间默认控制器
    get '', to: 'static_pages#home', as: '/'
    get 'static_pages', to: 'static_pages#home', as: 'static_pages/'
    get 'static_pages/home'
  end


  ##AUTHENTICATION
  namespace :admin do
    #跳转至登录界面；
    get 'logout', to: 'login#logout', as: 'logout/'
    get 'login/logout'

    #跳转至登录界面；
    get 'login', to: 'login#login', as: 'login/'
    get 'login/login'

    #表单提交验证；
    post 'login', to: 'login#signin', as: 'signin/'
    post 'login/signin'

    #跳转至主界面；
    get 'main', to: 'main#index', as: 'main/'
    get 'main/index'
    get '/', to: 'main#index', as: '/'

    resources :users

    resources :channels
  end

  #root 'index.html'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/menu.rb
class Admin::Menu < ApplicationRecord
    attr_accessor :children;
    
    #初始化数组；
    #def initialize()
        #@children = ["123",123];
    #end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::AuthencatedController
  before_action :set_admin_menu, only: [:show, :edit, :update, :destroy]

  # GET /admin/menus
  # GET /admin/menus.json
  def index
    @admin_menus = Admin::Menu.all
  end

  # GET /admin/menus/1
  # GET /admin/menus/1.json
  def show
  end

  # GET /admin/menus/new
  def new
    @admin_menu = Admin::Menu.new
  end

  # GET /admin/menus/1/edit
  def edit
  end

  # POST /admin/menus
  # POST /admin/menus.json
  def create
    @admin_menu = Admin::Menu.new(admin_menu_params)

    respond_to do |format|
      if @admin_menu.save
        format.html { redirect_to @admin_menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @admin_menu }
      else
        format.html { render :new }
        format.json { render json: @admin_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/menus/1
  # PATCH/PUT /admin/menus/1.json
  def update
    respond_to do |format|
      if @admin_menu.update(admin_menu_params)
        format.html { redirect_to @admin_menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_menu }
      else
        format.html { render :edit }
        format.json { render json: @admin_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/menus/1
  # DELETE /admin/menus/1.json
  def destroy
    @admin_menu.destroy
    respond_to do |format|
      format.html { redirect_to admin_menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_menu
      @admin_menu = Admin::Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_menu_params
      params.require(:admin_menu).permit(:name, :url, :icon, :icon_location, :created_by, :updated_by, :enabled, :is_enabled, :is_locked, :is_expired, :status, :type, :parent_id)
    end
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/views/admin/menus/_form.html.erb
<%= form_for(admin_menu, html: {class: "form-horizontal",style:"max-width: 600px;"})  do |f| %>
  <% if admin_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_menu.errors.count, "error") %> prohibited this admin_menu from being saved:</h2>

      <ul>
      <% admin_menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.label :name ,"名称",class:"col-md-2 control-label",style:"color:red"%>
  <div class="col-md-10">
    <%= f.text_field :name , size: "30", class:"form-control" , placeholder:"名称",required:true %>
  </div>
</div>

<div class="form-group">
  <%= f.label :url ,"连接",class:"col-md-2 control-label",style:"color:red"%>
  <div class="col-md-10">
    <%= f.text_field :url , class:"form-control" , placeholder:"连接",required:true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :parent_id ,"父亲",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.number_field :parent_id %>
  </div>
</div>

<div class="form-group">
  <%= f.label :icon ,"图标",class:"col-md-2 control-label",style:"color:red"%>
  <div class="col-md-10">
    <%= f.text_field :icon , class:"form-control" , placeholder:"图标",required:true %>
  </div>
</div>
 
<div class="form-group">
  <%= f.label :is_enabled  ,"是否可用",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <div class="radio">
      <label>
        <%=f.radio_button(:is_enabled, true)%>是
      </label>
      <label>
        <%=f.radio_button(:is_enabled, false)%>否
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :is_locked ,"是否锁定",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <div class="radio">
      <label>
        <%=f.radio_button(:is_locked, true)%>是
      </label>
      <label>
        <%=f.radio_button(:is_locked, false)%>否
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :is_expired ,"是否过期",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <div class="radio">
      <label>
        <%=f.radio_button(:is_expired, true)%>是
      </label>
      <label>
        <%=f.radio_button(:is_expired, false)%>否
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :status,"状态",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.number_field :status %>
  </div>
</div>

<div class="form-group">
  <%= f.label :type ,"类型",class:"col-md-2 control-label"%>
  <div class="col-md-10">
    <%= f.number_field :type %>
  </div>
</div>

<div class="actions form-group">
  <div class="col-md-2"></div>
  <div class="col-md-10">
    <%= f.submit "提交", class:"btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/admin/menus/_index.html.erb
<ul class="breadcrumb">
  <li><a href="/admin/main">首页</a></li>
  <li><a href="/admin/menus" class="active">菜单管理</a></li>
</ul>
<p id="notice"><%= notice %></p>
<h4 class="sub-header">菜单列表</h4>
<%= link_to raw("<i class=\"fa fa-plus\" aria-hidden=\"true\">&nbsp;添加菜单</i>"), new_admin_menu_path  ,{ class:'btn btn-success'}%>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>名称</th>
        <th>Url</th>
        <th>图标</th>
        <th style="text-align: center;">是否可用</th>
        <th style="text-align: center;">是否锁定</th>
        <th style="text-align: center;">是否过期</th>
        <th style="text-align: center;">类型</th>
        <th colspan="3" style="text-align: center;">操作</th>
      </tr>
    </thead>


    <tbody>
      <% @admin_menus.each do |admin_menu| %>
      <tr>
        <td><%= admin_menu.name %></td>
        <td><%= admin_menu.url %></td>
        <td><%= (admin_menu.icon).html_safe %></td>
        <td style="text-align: center;">
          <label>
            <% if admin_menu.is_enabled== true %>
            <%= "是"%>
            <% else %>
            <%= "否"%>
            <% end %>
          </label>
        </td>
        <td style="text-align: center;">
          <label>
            <% if admin_menu.is_locked== true %>
            <%= "是"%>
            <% else %>
            <%= "否"%>
            <% end %>
          </label>
        </td>
        <td style="text-align: center;">
          <label>
            <% if admin_menu.is_expired== true %>
            <%= "是"%>
            <% else %>
            <%= "否"%>
            <% end %>
          </label>
        </td>
        <td><%= admin_menu.type %></td>
        <td>
          <%= link_to raw("<i class=\"fa fa-info-circle\" aria-hidden=\"true\">&nbsp;详情</i>"), admin_menu ,{ class:'btn btn-info'}%>
        </td>
        <td>
          <%= link_to raw("<i class=\"fa fa-wrench\" aria-hidden=\"true\">&nbsp;编辑</i>"), edit_admin_menu_path(admin_menu) ,{ class:'btn btn-warning'}%>
        </td>
        <td>
          <%= link_to raw("<i class=\"fa fa-trash\" aria-hidden=\"true\">&nbsp;删除</i>"), admin_menu, method: :delete, data: { confirm: '你确定删除该条目吗?' },class:'btn btn-danger'%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/menus/edit.html.erb
<%@title="管理后台菜单编辑页"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar" , select_menu: "/admin/menus" %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <ul class="breadcrumb">
          <li><a href="/admin/main">首页</a></li>
          <li><a href="/admin/menus" class="active">菜单管理</a></li>
        </ul>
        <h4 class="sub-header">菜单编辑</h4>
        <%= render 'form', admin_menu: @admin_menu %>
        <%= link_to raw("<i class=\"fa fa-wrench\" aria-hidden=\"true\">&nbsp;详情</i>"), @admin_menu ,{ class:'btn btn-info'}%>
        <%= link_to raw("<i class=\"fa fa-arrow-circle-left\" aria-hidden=\"true\">&nbsp;返回</i>"), admin_menus_path ,{ class:'btn btn-primary'}%>
    </div>  
  </div>
</div>
<script type="text/javascript">
    $(function(){ 
　　  //document.getElementById("admin_menu_menuname").disabled=true;
        //$('#admin_menu_menuname').attr("disabled",true);
　　});
</script>

app/views/admin/menus/index.html.erb
<%@title="管理后台菜单管理"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar", select_menu: "/admin/menus" %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <%= render "admin/menus/index"%> 
    </div>  
  </div>
</div>

app/views/admin/menus/new.html.erb
<%@title="管理后台新建菜单"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar", select_menu: "/admin/menus"  %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <ul class="breadcrumb">
          <li><a href="/admin/main">首页</a></li>
          <li><a href="/admin/menus" class="active">菜单管理</a></li>
          <%# <li><a class="active">菜单新增</a></li> %>
      </ul>
      <h4 class="sub-header">新建菜单</h4>
      
      <%= render 'form', admin_menu: @admin_menu %>
      <%= link_to raw("<i class=\"fa fa-arrow-circle-left\" aria-hidden=\"true\">&nbsp;返回</i>"), admin_menus_path ,{ class:'btn btn-primary'}%>
    </div>  
  </div>
</div>

app/views/admin/menus/show.html.erb
<%@title="管理后台菜单详情"%>
<%= render "admin/share/header" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render "admin/share/sidebar", select_menu: "/admin/menus"  %>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <ul class="breadcrumb">
          <li><a href="/admin/main">首页</a></li>
          <li><a href="/admin/menus" class="active">菜单管理</a></li>
          <%# <li><a href="#" class="active">菜单详情</a></li> %>
      </ul>
        <h4 class="sub-header">菜单详情</h4>
        <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_menu.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @admin_menu.url %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @admin_menu.icon %>
</p>

<p>
  <strong>Icon location:</strong>
  <%= @admin_menu.icon_location %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @admin_menu.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @admin_menu.updated_by %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @admin_menu.enabled %>
</p>

<p>
  <strong>Is enabled:</strong>
  <%= @admin_menu.is_enabled %>
</p>

<p>
  <strong>Is locked:</strong>
  <%= @admin_menu.is_locked %>
</p>

<p>
  <strong>Is expired:</strong>
  <%= @admin_menu.is_expired %>
</p>

<p>
  <strong>Status:</strong>
  <%= @admin_menu.status %>
</p>

<p>
  <strong>Type:</strong>
  <%= @admin_menu.type %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @admin_menu.parent_id %>
</p>
        <%= link_to raw("<i class=\"fa fa-wrench\" aria-hidden=\"true\">&nbsp;编辑</i>"), edit_admin_menu_path(@admin_menu) ,{ class:'btn btn-warning'}%>
        <%= link_to raw("<i class=\"fa fa-arrow-circle-left\" aria-hidden=\"true\">&nbsp;返回</i>"), admin_menus_path ,{ class:'btn btn-primary'}%>

    </div>  
  </div>
</div>